using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using UnityEngine;

public static class SeedProcessor {

	private static Hash128 _hash;
	private static int currByteIdx;

	public static void initSeed(string seed = "") {

		_hash = new Hash128();
		// _hash.Append(seed);
		_hash.Append(DateTime.Now.ToString(CultureInfo.CurrentCulture));
	}

	// This method allows to iterate the bytes generated by hash function.
	public static int getNextByteValue() {
		var byteAsSubstring = "0x" + _hash.ToString().Substring(currByteIdx * 2, 2);

		++currByteIdx;
		if (currByteIdx >= 16) {
			currByteIdx = 0;
		}

		return Convert.ToInt32(byteAsSubstring, 16);
	}

}
